### ISSUE TITLE
[BUG] No button for WiFi connect to printer on Cura 4.9.0

### ISSUE THREAD

**Issue by Pro-serj** [Jeredian/mks-wifi-plugin#154] opened 2021-04-23 19:32 UTC
**Describe the bug**
No button for WiFi connect to printer on Cura 4.9.0

**To Reproduce**
1. Update Cura from 4.8 to 4.9
2. install MKS WiFi plugin
3. No button for WiFi connect to printer

**Expected behavior**
Connection to printer by Wifi

**Screenshots**
![Cura_4-9_MKS_WiFi_not_working_Screenshot_1](https://user-images.githubusercontent.com/83091625/115920874-737a5480-a483-11eb-8312-1e6bb8384ac8.png)
![Cura_4-9_MKS_WiFi_not_working_Screenshot_2](https://user-images.githubusercontent.com/83091625/115920897-7bd28f80-a483-11eb-8082-0c63c8e4ecd2.png)
![Cura_4-9_MKS_WiFi_not_working_Screenshot_3](https://user-images.githubusercontent.com/83091625/115920918-81c87080-a483-11eb-9c25-e54019ca00e0.png)

Desktop (please complete the following information):
 - OS:  Windows 10
 - Cura version:  4.9.0
 - Plugin version: 1.2.1
 - 3D printer: FlyingBear Ghost 5
 - Motherboard and/or WiFi module firmware version: V5.8-T25

There is no button to connect to Printer by WiFi
On Cura 4.8.0 it was working, but sometimes if conncected to printer and closed Cura (without disconnection) can't connect after restarting Cura... But after updating Cura to 4.9.0 it does not show any button to connect to printer.

**Comment by wkoetz** [comment] 2021-04-23 23:25
Did you try this workaround?
https://github.com/Jeredian/mks-wifi-plugin/issues/148#issuecomment-822040166

**Comment by Pro-serj** [comment] 2021-04-24 15:13
Yes I did, but even the folder name isn't same as described in Mac...

**Comment by wkoetz** [comment] 2021-04-24 16:29
I have done this patch. It works well.

**Comment by Jeredian** [comment] 2021-04-24 23:28
@Pro-serj , FYI please check already existed issues instead of making a duplicate issue.

About file folder, RTFM . 
• Windows: %APPDATA%\cura\ , or C:\Users\AppData\Roaming\cura\
• OSX: $USER/Library/Application Support/cura/
• Linux: $USER/.local/share/cura/
inside that folder, you need to go inside "cura-version" -> "plugins folder" -> "mks wifi plugin folder".

**Comment by Jeredian** [comment] 2021-04-24 23:29
Duplicates #148 , #150

**Comment by Jeredian** [comment] 2021-04-24 23:29
Duplicate of #148

**Closed as completed** 2021-04-24 23:30 UTC
Labels: status: duplicate
