### ISSUE TITLE
1.2.6 Remove function does not work

### ISSUE THREAD

**Issue by UncleJessy** [Jeredian/mks-wifi-plugin#260] opened 2021-12-31 16:33 UTC
### Plugin Version

1.2.6

### Cura Version

4.12.1

### Platform

MAC oS

### Printer

Neptune 2

### Reproduction steps

1. Setup MKS Plugin
2. Assign IP address
3. Connect to Printer
4. Disconnect from Printer
5. Click Remove

### Actual results

When attempting to Remove a connection entry nothing happens. 
If you Restart Cura and try to remove - it will not remove
If you uninstall the plugin - restart cura, reinstall the plugin, restart cura - you still cannot remove the wifi entry

### Expected results

You should be able to select a wifi entry and click remove and it remove the IP Address entry. 

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Jeredian/mks-wifi-plugin/files/7796660/cura.log)

**Comment by Jeredian** [comment] 2022-01-09 09:54
@UncleJessy , can you try the same thing but with latest version from develop branch? (you will need to replace files at the Library/Application Support/cura/4.12/plugins/MKSWifiPlugin/MKSWifiPlugin folder)
Because I tried for 4.12 and 4.13 versions of the Cura and I can't reproduce your issue.

**Comment by Jeredian** [comment] 2022-01-22 21:12
@Elkin-Vasily , please try to reproduce it too, because I can not. If it does not appear for latest version of the plugin, let's close this issue.

**Comment by Jeredian** [comment] 2022-02-06 14:43
closed due inactivity

**Closed as completed by Jeredian** 2022-02-06 14:43 UTC
