### ISSUE TITLE
Reconnect loop problem

### ISSUE THREAD

**Issue by iqubik** [Jeredian/mks-wifi-plugin#289] opened 2022-05-09 12:38 UTC
### Plugin Version

1.3.2

### Cura Version

4.13.1

### Platform

windows 10

### Printer

flsun q5

### Reproduction steps

1. Start cura
2. Printer is connect
3. Disconnect
4. Connect
5. Disconnect

### Actual results

loop connection and disconnection

### Expected results

Please fix this

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Jeredian/mks-wifi-plugin/files/8651672/cura.log)

**Comment by ParkerK** [comment] 2022-05-10 21:56
Hi @iqubik This issue is a duplicate of https://github.com/Jeredian/mks-wifi-plugin/issues/281. Please refer to that issue for the latest updates and the fix :)

**Closed as completed** 2022-05-11 12:32 UTC
Labels: status: duplicate
