### ISSUE TITLE
the plugin dosen't work with 4.9

### ISSUE THREAD

**Issue by msmeeh** [Jeredian/mks-wifi-plugin#151] opened 2021-04-21 17:06 UTC
the pulgin doesn't work with Cura 4.9, please update it or give solution

**Comment by JonathanMortes** [comment] 2021-04-22 06:43
It doesn't work either with 4.7.1 either. I've got their software and HW (MKS robin e3p and TFT35) and it won't show me the preview on the machine and sometimes it will even fail. All I get is a G on the screen

**Comment by Jeredian** [comment] 2021-04-23 07:57
@JonathanMortes , at now plugin, support Cura from 4.5 to 4.8, so it can be installed from Cura Marketplace and connect to the printer.
About preview, since the latest update, was moved to the plugin settings, you can check "image settings" at the same place where you add IP settings for your printer.

**Comment by Jeredian** [comment] 2021-04-23 08:01
@msmeeh , FYI please check already existed issues instead of making a duplicate issue with so obvious thing
you can look to this #148

**Comment by Jeredian** [comment] 2021-04-23 08:01
Duplicate of #148

**Closed as completed by Jeredian** 2021-04-23 08:01 UTC
Labels: status: duplicate
