### ISSUE TITLE
does not work in Cura 4.10.0

### ISSUE THREAD

**Issue by Ignat-8** [Jeredian/mks-wifi-plugin#173] opened 2021-06-30 13:11 UTC
Hello, this plugin does not work in Cura 4.10.0

**Comment by metjuzlyapar** [comment] 2021-06-30 14:52
i have encounted the same issue in Cura 4.10

**Comment by Jeredian** [comment] 2021-07-01 10:29
It should not because the max supported version is 4.9.0. Support of 4.10 will be at the start of the next week in dev branch. #171

**Comment by Jeredian** [comment] 2021-07-01 10:30
Duplicate of #171

**Closed as completed** 2021-07-10 08:30 UTC
