### ISSUE TITLE
[BUG] No working with new version 4.9.0

### ISSUE THREAD

**Issue by ginolatilla123** [Jeredian/mks-wifi-plugin#153] opened 2021-04-23 18:20 UTC
**Describe the bug**
Hello, after the upgrade to newest Cura version, 4.9.0 the button into Printer Management form is disappeared and even under control panel the remote printer is no more available, not working even delete and re-copy files into plugin folder neither add plugin from Cura's website

**To Reproduce**
Simply upgrade to 4.9.0 and you won't find the plugin buttons/interface

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Cura version: 4.9.0
 - Plugin version: 1.1.2
 - 3D printer: FlyingBear Ghost 5
 - Motherboard and/or WiFi module firmware version: Ver.5.8

**Comment by Elkin-Vasily** [comment] 2021-04-24 17:48
Duplicate of #148

**Closed as completed by Elkin-Vasily** 2021-04-24 17:48 UTC
Labels: status: duplicate
